dsquery user -samid degetst3
dsquery user -samid btreffle
dsquery user -samid chltgene
dsquery user -samid tkronth1
dsquery user -samid tkronth2
dsquery user -samid dege0064
dsquery user -samid dege0069
dsquery user -samid degea018
dsquery user -samid fasam
dsquery user -samid hschmutz
dsquery user -samid degeaz005
dsquery user -samid ipommera
dsquery user -samid jdobbers
dsquery user -samid a
dsquery user -samid aaatester
dsquery user -samid tstoerr1
dsquery user -samid degemuc2
dsquery user -samid #sdege_tcprocess
dsquery user -samid degeaz16
dsquery user -samid dege00117
dsquery user -samid dege00115
dsquery user -samid cfraefel
dsquery user -samid swolf2
dsquery user -samid degemat1
