dsquery user -samid pmendoz1
dsquery user -samid narana
dsquery user -samid aserrato
dsquery user -samid egarcia2
dsquery user -samid svallejo
dsquery user -samid ldeloza
dsquery user -samid emaya
dsquery user -samid orocha
dsquery user -samid mhernan4
dsquery user -samid fperez5
dsquery user -samid lhernan2
dsquery user -samid vramos
dsquery user -samid vmedina
dsquery user -samid ebernal
dsquery user -samid mfragos1
dsquery user -samid dllanos
dsquery user -samid rbuendia
dsquery user -samid bnegrete
dsquery user -samid jtrenado
dsquery user -samid dmendez1